version: "3.7"

services:
  server-amd64:
    build:
      context: .
      dockerfile: Dockerfile.amd64
    ports:
      - ${PORT}:${PORT}
    environment:
      TZ: Asia/Tokyo
      PORT: ${PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ADDR: ${MYSQL_ADDR}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - mysql

  server-arm64:
    build:
      context: .
      dockerfile: Dockerfile.arm64
    ports:
      - ${PORT}:${PORT}
    environment:
      TZ: Asia/Tokyo
      PORT: ${PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ADDR: ${MYSQL_ADDR}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - mysql

  mysql:
    # M1 macの人のみ必要
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
