CREATE TABLE
    IF NOT EXISTS rooms (
        id INT(11) AUTO_INCREMENT COMMENT "ルームID",
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT "ルーム作成日時",
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT "ルーム更新日時",
        deteled_at DATETIME COMMENT "ルーム論理削除日時",
        PRIMARY KEY (id)
    ) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COMMENT = 'ルーム';
