// Code generated by SQLBoiler 4.12.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	Messages          string
	RoomUsers         string
	Rooms             string
	UserProfileImages string
	Users             string
}{
	Messages:          "messages",
	RoomUsers:         "room_users",
	Rooms:             "rooms",
	UserProfileImages: "user_profile_images",
	Users:             "users",
}
