// Code generated by SQLBoiler 4.12.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	SchemaMigrations string
	User             string
	UserProfileImage string
}{
	SchemaMigrations: "schema_migrations",
	User:             "user",
	UserProfileImage: "user_profile_image",
}
